### ISSUE TITLE
Upgrade to current Swift

### ISSUE THREAD

**Issue by kiliankoe** [swiftde/SwiftDEBot#17]
Unfortunately blocked by https://github.com/Azoy/Sword.git being archived and unmaintained. Is there a better Swift Discord package alternative?

This is a bug because it's super painful.

**Comment by kiliankoe** [comment]
https://swiftpackageindex.com/MahdiBM/DiscordBM looks promising!

**Comment by GrahamBarayTt** [comment]
I see on https://swiftpackageindex.com/MahdiBM/DiscordBM.

Hopefully, this new package will help us get past this bug and upgrade to the latest version of Swift.
